# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish to PyPI

on:
  workflow_dispatch
#  push:
#    tags: '^[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install system dependencies
        run: |
          sudo apt install pandoc

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest tox

      - name: Build package
        run: |
          python -m tox -e clean,build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
